version: "3.9"

services:
  project-service:
    build:
      context: ./project-service
    container_name: project-service
    ports:
      - "8000:8000"
    restart: always

  user-service-1:
    build:
      context: ./user-service
    command: uvicorn app:app --host 0.0.0.0 --port 8001
    container_name: user-service-1
    restart: always

  user-service-2:
    build:
      context: ./user-service
    command: uvicorn app:app --host 0.0.0.0 --port 8002
    container_name: user-service-2
    restart: always

  user-service-3:
    build:
      context: ./user-service
    command: uvicorn app:app --host 0.0.0.0 --port 8003
    container_name: user-service-3
    restart: always

  nginx:
    image: nginx:latest
    container_name: user-service-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service-1
      - user-service-2
      - user-service-3
    restart: always
