services:
  user-service-1:
    build: ./user-service
    container_name: user-service-1
    ports:
      - "8001:8001"
    networks:
      - unicollab-network

  user-service-2:
    build: ./user-service
    container_name: user-service-2
    ports:
      - "8002:8001"
    networks:
      - unicollab-network

  user-service-3:
    build: ./user-service
    container_name: user-service-3
    ports:
      - "8003:8001"
    networks:
      - unicollab-network

  project-service:
    build: ./project-service
    container_name: project-service
    ports:
      - "8000:8000"
    networks:
      - unicollab-network

  user-service-nginx:
    image: nginx:latest
    container_name: user-service-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service-1
      - user-service-2
      - user-service-3
    networks:
      - unicollab-network

networks:
  unicollab-network:
    driver: bridge
