services:
  user-service-1:
    build: .
    container_name: user-service-1
    ports:
      - "8001:8001"
    env_file:
      - .env
    command: uvicorn app:app --host 0.0.0.0 --port 8001
    restart: always

  user-service-2:
    build: .
    container_name: user-service-2
    ports:
      - "8002:8002"
    env_file:
      - .env
    command: uvicorn app:app --host 0.0.0.0 --port 8002
    restart: always

  user-service-3:
    build: .
    container_name: user-service-3
    ports:
      - "8003:8003"
    env_file:
      - .env
    command: uvicorn app:app --host 0.0.0.0 --port 8003
    restart: always

  nginx:
    image: nginx:latest
    container_name: user-service-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service-1
      - user-service-2
      - user-service-3
    restart: always
